# Generated by Django 2.2 on 2022-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('des', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('creater', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('Line', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('email_to', models.CharField(blank=True, default='[]', max_length=500, null=True)),
                ('sql_host', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sql_port', models.IntegerField(default=0)),
                ('sql_user', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sql_pwd', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sql_db', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('doing_api', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('end_result', models.TextField(default='')),
                ('dck', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
