# Generated by Django 2.2 on 2022-08-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_db_project_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_project_list',
        ),
    ]
