# Generated by Django 2.2 on 2022-08-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_delete_db_project_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_news',
        ),
    ]
