# Generated by Django 2.2 on 2022-08-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0006_db_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='Line',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='dck',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='doing_api',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='email_to',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='end_result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_db',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_host',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_pwd',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_user',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
